
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./Quest")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def Next():
    window.destroy()
    import Cust
window = Tk()

window.geometry("1268x799")
window.configure(bg = "#000000")


canvas = Canvas(
    window,
    bg = "#000000",
    height = 799,
    width = 1268,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    317.0,
    347.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    951.0,
    399.0,
    image=image_image_2
)

canvas.create_text(
    854.0,
    56.0,
    anchor="nw",
    text="Quest",
    fill="#FFFFFF",
    font=("GRANDGALAXY", 39 * -1)
)

canvas.create_text(
    708.0,
    195.0,
    anchor="nw",
    text="QUESTIOn text hereeeeee\neeeeeeeeeeeeeeeeeeee",
    fill="#FFFFFF",
    font=("GRANDGALAXY", 24 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=672.0,
    y=296.0,
    width=558.0,
    height=80.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=672.0,
    y=408.0,
    width=558.0,
    height=80.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=672.0,
    y=520.0,
    width=558.0,
    height=80.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=672.0,
    y=643.0,
    width=558.0,
    height=80.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=Next,
    relief="flat"
)
button_5.place(
    x=122.0,
    y=669.0,
    width=391.0,
    height=107.0
)
window.resizable(False, False)
window.mainloop()
