
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import *
import tkinter as tk
from PIL import Image,ImageTk,ImageSequence
import threading
from time import sleep
import _thread
import mouse

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./Start")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1268x799")
window.configure(bg = "#FFFFFF")

Animation="assets\StartScreen.gif"


def Next():
    window.destroy()
    import Quest
canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 799,
    width = 1268,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)


canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    634.0000000000002,
    399.9999999999998,
    image=image_image_1
)

canvas.create_text(
    124.99999999999977,
    651.0000000000002,
    anchor="nw",
    text="-----   Lets Start Jupiterization   -----",
    fill="#FFFFFF",
    font=("GRANDGALAXY", 39 * -1)
)
Flag= False

mouse.on_click(lambda: Flag==True)
if Flag:
    Next()
    

window.resizable(False, False)
window.mainloop()

